import { Category, Product, LocalizedString, UserRecord } from './types';

export const UI_STRINGS: { [key: string]: LocalizedString } = {
  storeName: { en: 'BALA STORE', te: 'బాల స్టోర్' },
  home: { en: 'Home', te: 'హోమ్' },
  orders: { en: 'My Orders', te: 'నా ఆర్డర్లు' },
  categories: { en: 'Product Categories', te: 'ఉత్పత్తి వర్గాలు' },
  searchPlaceholder: { en: 'Search for products...', te: 'ఉత్పత్తుల కోసం శోధించండి...' },
  addToCart: { en: 'Add to Cart', te: 'కార్ట్‌కు జోడించండి' },
  shoppingCart: { en: 'Shopping Cart', te: 'షాపింగ్ కార్ట్' },
  emptyCart: { en: 'Your cart is empty.', te: 'మీ కార్ట్ ఖాళీగా ఉంది.' },
  total: { en: 'Total', te: 'మొత్తం' },
  placeOrder: { en: 'Place Order', te: 'ఆర్డర్ చేయండి' },
  orderHistory: { en: 'Order History', te: 'ఆర్డర్ చరిత్ర' },
  noOrders: { en: 'You have not placed any orders yet.', te: 'మీరు ఇంకా ఆర్డర్లు చేయలేదు.' },
  orderId: { en: 'Order ID', te: 'ఆర్డర్ ID' },
  date: { en: 'Date', te: 'తేదీ' },
  status: { en: 'Status', te: 'స్థితి' },
  items: { en: 'Items', te: 'వస్తువులు' },
  backToProducts: { en: 'Back to Products', te: 'ఉత్పత్తులకు తిరిగి వెళ్ళు' },
  backToHome: { en: 'Back to Categories', te: 'వర్గాలకు తిరిగి వెళ్ళు' },
  processing: { en: 'Processing', te: 'ప్రాసెసింగ్‌లో ఉంది' },
  outForDelivery: { en: 'Out for Delivery', te: 'డెలివరీకి బయలుదేరింది' },
  delivered: { en: 'Delivered', te: 'డెలివరీ చేయబడింది' },
  logout: { en: 'Logout', te: 'లాగ్ అవుట్' },
  selectPaymentMethod: { en: 'Select Payment Method', te: 'చెల్లింపు పద్ధతిని ఎంచుకోండి' },
  cashOnDelivery: { en: 'Cash on Delivery', te: 'క్యాష్ ఆన్ డెలివరీ' },
  upiPayment: { en: 'UPI Payment', te: 'UPI చెల్లింపు' },
  payWithUPI: { en: 'Pay with UPI', te: 'UPIతో చెల్లించండి' },
  storeUpiId: { en: 'Store UPI ID', te: 'స్టోర్ UPI ID' },
  paymentInstructions: { en: 'Scan the QR or use the UPI ID to pay. After payment, click the button below to confirm your order.', te: 'చెల్లించడానికి QRని స్కాన్ చేయండి లేదా UPI IDని ఉపయోగించండి. చెల్లింపు తర్వాత, మీ ఆర్డర్‌ను నిర్ధారించడానికి దిగువ బటన్‌ను క్లిక్ చేయండి.' },
  confirmPayment: { en: 'I Have Paid & Confirm Order', te: 'నేను చెల్లించాను & ఆర్డర్‌ను నిర్ధారించండి' },
  cancel: { en: 'Cancel', te: 'రద్దు చేయి' },
  paymentMethod: { en: 'Payment Method', te: 'చెల్లింపు విధానం' },
  paymentStatus: { en: 'Payment Status', te: 'చెల్లింపు స్థితి' },
  paid: { en: 'Paid', te: 'చెల్లించబడింది' },
  pending: { en: 'Pending', te: 'పెండింగ్‌లో ఉంది' },
  manageProducts: { en: 'Manage Products', te: 'ఉత్పత్తులను నిర్వహించండి' },
  transactionHistory: { en: 'Transaction History', te: 'లావాదేవీల చరిత్ర' },
  inStock: { en: 'In Stock', te: 'స్టాక్‌లో ఉంది' },
  outOfStock: { en: 'Out of Stock', te: 'స్టాక్ లేదు' },
  delete: { en: 'Delete', te: 'తొలగించు' },
  size: { en: 'Size / Weight', te: 'పరిమాణం / బరువు' },
  stockStatus: { en: 'Stock Status', te: 'స్టాక్ స్థితి' },
  actions: { en: 'Actions', te: 'చర్యలు' },
  productManagement: { en: 'Product Management', te: 'ఉత్పత్తి నిర్వహణ' },
  allTransactions: { en: 'All Transactions', te: 'అన్ని లావాదేవీలు' },
  manageOrders: { en: 'Manage Orders', te: 'ఆర్డర్‌లను నిర్వహించండి' },
  addProduct: { en: 'Add Product', te: 'ఉత్పత్తిని జోడించండి' },
  addCategory: { en: 'Add Category', te: 'వర్గాన్ని జోడించండి' },
  edit: { en: 'Edit', te: 'సవరించు' },
  editProduct: { en: 'Edit Product', te: 'ఉత్పత్తిని సవరించండి' },
  saveChanges: { en: 'Save Changes', te: 'మార్పులను భద్రపరచు' },
  signInWithGoogle: { en: 'Sign in with Google', te: 'Googleతో సైన్ ఇన్ చేయండి' },
  customerDetails: { en: 'Delivery Details', te: 'డెలివరీ వివరాలు' },
  customerName: { en: 'Full Name', te: 'పూర్తి పేరు' },
  customerMobile: { en: 'Mobile Number', te: 'మొబైల్ నంబర్' },
  address: { en: 'Full Address', te: 'పూర్తి చిరునామా' },
  proceedToPayment: { en: 'Proceed to Payment', te: 'చెల్లింపుకు కొనసాగండి' },
  manageUsers: { en: 'Manage Users', te: 'వినియోగదారులను నిర్వహించండి' },
  userManagement: { en: 'User Management', te: 'వినియోగదారు నిర్వహణ' },
  editUser: { en: 'Edit User', te: 'వినియోగదారుని సవరించండి' },
  email: { en: 'Email', te: 'ఇమెయిల్' },
  mobile: { en: 'Mobile', te: 'మొబైల్' },
  role: { en: 'Role', te: 'పాత్ర' },
  newPassword: { en: 'New Password (optional)', te: 'కొత్త పాస్‌వర్డ్ (ఐచ్ఛికం)' },
  storeSettings: { en: 'Store Settings', te: 'స్టోర్ సెట్టింగ్‌లు' },
  upiSettings: { en: 'UPI Payment Settings', te: 'UPI చెల్లింపు సెట్టింగ్‌లు' },
  upiId: { en: 'Your UPI ID', te: 'మీ UPI ID' },
  qrCodeImage: { en: 'QR Code Image', te: 'QR కోడ్ చిత్రం' },
  uploadQrCode: { en: 'Upload a QR Code Image', te: 'QR కోడ్ చిత్రాన్ని అప్‌లోడ్ చేయండి' },
  settingsSaved: { en: 'Settings saved successfully!', te: 'సెట్టింగ్‌లు విజయవంతంగా సేవ్ చేయబడ్డాయి!' },
  share: { en: 'Share', te: 'పంచుకోండి' },
  dataManagement: { en: 'Import / Export Data', te: 'డేటాను దిగుమతి / ఎగుమతి చేయండి' },
  exportData: { en: 'Export All Data', te: 'మొత్తం డేటాను ఎగుమతి చేయండి' },
  exportDescription: { en: 'Save a backup of all products, categories, orders, users, and settings to a file.', te: 'అన్ని ఉత్పత్తులు, వర్గాలు, ఆర్డర్లు, వినియోగదారులు మరియు సెట్టింగ్‌ల బ్యాకప్‌ను ఫైల్‌లో సేవ్ చేయండి.' },
  importData: { en: 'Import Data', te: 'డేటాను దిగుమతి చేయండి' },
  importDescription: { en: 'Restore data from a backup file. This will overwrite all current data.', te: 'బ్యాకప్ ఫైల్ నుండి డేటాను పునరుద్ధరించండి. ఇది ప్రస్తుత డేటా మొత్తాన్ని ఓవర్రైట్ చేస్తుంది.' },
  importConfirm: { en: 'Are you sure you want to import data? This will overwrite all existing products, categories, orders, users, and settings. This action cannot be undone.', te: 'మీరు డేటాను దిగుమతి చేయాలనుకుంటున్నారని ఖచ్చితంగా అనుకుంటున్నారా? ఇది ఇప్పటికే ఉన్న అన్ని ఉత్పత్తులు, వర్గాలు, ఆర్డర్లు, వినియోగదారులు మరియు సెట్టింగ్‌లను ఓవర్రైట్ చేస్తుంది. ఈ చర్యను రద్దు చేయడం సాధ్యం కాదు.' },
  manageCategories: { en: 'Manage Categories', te: 'వర్గాలను నిర్వహించండి' },
  editCategory: { en: 'Edit Category', te: 'వర్గాన్ని సవరించండి' },
};

export const DUMMY_USERS: UserRecord[] = [
  { id: 'admin1', name: 'Admin Bala', email: 'admin@store.com', mobile: '1234567890', pass: 'admin123', role: 'admin' },
  { id: 'user1', name: 'Test User', email: 'user@store.com', mobile: '9876543210', pass: 'user123', role: 'user' },
  { id: 'google_user', name: 'Google User', email: 'google.user@gmail.com', mobile: '1112223334', role: 'user' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'groceries', name: { en: 'Groceries', te: 'కిరాణా' }, image: 'https://picsum.photos/seed/groceries/400/300' },
  { id: 'household', name: { en: 'Household Items', te: 'గృహోపకరణాలు' }, image: 'https://picsum.photos/seed/household/400/300' },
  { id: 'snacks', name: { en: 'Snacks & Beverages', te: 'చిరుతిళ్లు & పానీయాలు' }, image: 'https://picsum.photos/seed/snacks/400/300' },
  { id: 'personal_care', name: { en: 'Personal Care', te: 'వ్యక్తిగత సంరక్షణ' }, image: 'https://picsum.photos/seed/personalcare/400/300' },
  { id: 'fancy', name: { en: 'Fancy Items', te: 'ఫ్యాన్సీ వస్తువులు' }, image: 'https://picsum.photos/seed/fancy/400/300' },
];

export const PRODUCTS: Product[] = [
  // Groceries
  { id: 'p1', name: { en: 'Sona Masoori Rice', te: 'సోనా మసూరి బియ్యం' }, size: '5kg', price: 350, image: 'https://picsum.photos/seed/rice/300/300', categoryId: 'groceries', stockStatus: 'In Stock' },
  { id: 'p2', name: { en: 'Toor Dal', te: 'కంది పప్పు' }, size: '1kg', price: 120, image: 'https://picsum.photos/seed/dal/300/300', categoryId: 'groceries', stockStatus: 'In Stock' },
  { id: 'p3', name: { en: 'Sunflower Oil', te: 'పొద్దుతిరుగుడు నూనె' }, size: '1L', price: 150, image: 'https://picsum.photos/seed/oil/300/300', categoryId: 'groceries', stockStatus: 'In Stock' },
  { id: 'p4', name: { en: 'Aashirvaad Atta', te: 'ఆశీర్వాద్ గోధుమ పిండి' }, size: '5kg', price: 250, image: 'https://picsum.photos/seed/atta/300/300', categoryId: 'groceries', stockStatus: 'In Stock' },
  
  // Household
  { id: 'p5', name: { en: 'Surf Excel Detergent', te: 'సర్ఫ్ ఎక్సెల్ డిటర్జెంట్' }, size: '1kg', price: 200, image: 'https://picsum.photos/seed/surf/300/300', categoryId: 'household', stockStatus: 'In Stock' },
  { id: 'p6', name: { en: 'Vim Dishwash Bar', te: 'విమ్ డిష్‌వాష్ బార్' }, price: 25, image: 'https://picsum.photos/seed/vim/300/300', categoryId: 'household', stockStatus: 'In Stock' },
  { id: 'p7', name: { en: 'Harpic Toilet Cleaner', te: 'హార్పిక్ టాయిలెట్ క్లీనర్' }, size: '500ml', price: 90, image: 'https://picsum.photos/seed/harpic/300/300', categoryId: 'household', stockStatus: 'In Stock' },

  // Snacks
  { id: 'p8', name: { en: 'Lays Potato Chips', te: 'లేస్ బంగాళాదుంప చిప్స్' }, price: 20, image: 'https://picsum.photos/seed/lays/300/300', categoryId: 'snacks', stockStatus: 'In Stock' },
  { id: 'p9', name: { en: 'Britannia Good Day Cookies', te: 'బ్రిటానియా గుడ్ డే కుకీలు' }, price: 30, image: 'https://picsum.photos/seed/goodday/300/300', categoryId: 'snacks', stockStatus: 'In Stock' },
  { id: 'p10', name: { en: 'Coca-Cola', te: 'కోకా-కోలా' }, size: '750ml', price: 40, image: 'https://picsum.photos/seed/coke/300/300', categoryId: 'snacks', stockStatus: 'In Stock' },

  // Personal Care
  { id: 'p11', name: { en: 'Colgate Toothpaste', te: 'కోల్గేట్ టూత్‌పేస్ట్' }, size: '100g', price: 55, image: 'https://picsum.photos/seed/colgate/300/300', categoryId: 'personal_care', stockStatus: 'In Stock' },
  { id: 'p12', name: { en: 'Lifebuoy Soap', te: 'లైఫ్‌బాయ్ సబ్బు' }, price: 30, image: 'https://picsum.photos/seed/lifebuoy/300/300', categoryId: 'personal_care', stockStatus: 'In Stock' },
  { id: 'p13', name: { en: 'Head & Shoulders Shampoo', te: 'హెడ్ & షోల్డర్స్ షాంపూ' }, size: '180ml', price: 150, image: 'https://picsum.photos/seed/shampoo/300/300', categoryId: 'personal_care', stockStatus: 'In Stock' },

  // Fancy
  { id: 'p14', name: { en: 'Fancy Hair Clips', te: 'ఫ్యాన్సీ హెయిర్ క్లిప్‌లు' }, size: 'Set of 6', price: 60, image: 'https://picsum.photos/seed/clips/300/300', categoryId: 'fancy', stockStatus: 'In Stock' },
  { id: 'p15', name: { en: 'Stud Earrings', te: 'స్టడ్ చెవిపోగులు' }, price: 120, image: 'https://picsum.photos/seed/earrings/300/300', categoryId: 'fancy', stockStatus: 'In Stock' },
  { id: 'p16', name: { en: 'Decorative Bindi Packet', te: 'అలంకార బిందీ ప్యాకెట్' }, price: 25, image: 'https://picsum.photos/seed/bindi/300/300', categoryId: 'fancy', stockStatus: 'In Stock' },
];
